ci:
  - .github/**/*

documentation:
  - docs/**/*
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - README.md
  - SECURITY.md

# Common
common:
  - common/**/*

# Plugin
plugin:
  - plugins/**/*
