[versions]
gradle = "7.5.1"
mkdocs = "3.0.0"
gradleCompositeDelegator = "0.1.0"

[plugins]
mkdocs = { id = "ru.vyarus.mkdocs", version.ref = "mkdocs" }
gradleCompositeDelegator = { id = "eu.bitfunk.gradle.plugin.tool.composite.delegator", version.ref = "gradleCompositeDelegator" }
