[versions]
bitfunkVersionCatalogAccessor = "0.1.0"
mkdocs = "2.2.0"


[plugins]
bitfunkVersionCatalogAccessor = { id = "eu.bitfunk.gradle.version.catalog", version.ref = "bitfunkVersionCatalogAccessor" }
mkdocs = { id = "ru.vyarus.mkdocs", version.ref = "mkdocs" }
