site_name: Gradle Plugins
site_description: Collection of Gradle plugins used across multiple projects.
site_author: Wolf-Martell Montwé
site_url: https://bitfunk.github.io/gradle-plugins/

repo_name: bitfunk/gradle-plugins
repo_url: https://github.com/bitfunk/gradle-plugins
edit_uri: edit/main/docs/src/

copyright: Copyright &copy; 2022 Wolf-Martell Montwé

docs_dir: src

extra_css:
  - assets/css/extra.css

theme:
  name: 'material'
  font: false
  language: en
  logo: assets/images/brand-logo.svg
  favicon: assets/images/logo.svg
  custom_dir: theme
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  social:
    - type: 'github'
      link: 'https://github.com/bitfunk/gradle-plugins'
  features:
    - navigation.tracking
    - navigation.top
    - navigation.indexes

plugins:
  - search
  - redirects
  - kroki
  - include-markdown
  - markdownextradata
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

extra:
  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bitfunk

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Plugins:
    - Overview: plugins/index.md
    - Quality:
      - All: plugins/quality/index.md
      - Code Analysis: plugins/quality/code-analysis/index.md
      - Formatter: plugins/quality/formatter/index.md
      - Report: plugins/quality/report/index.md
    - Tool:
        - Composite Delegator: plugins/tool/compositeDelegator/index.md
        - Publish: plugins/tool/publish/index.md
        - Version: plugins/tool/versioning/index.md
  - Plugin Development:
    - Overview: pluginDevelopment/index.md
    - GradlePluginConvention: pluginDevelopment/gradlePluginConvention/index.md
    - VersionCatalogAccessor: pluginDevelopment/versionCatalogAccessor/index.md
  - Develop:
      - Code of Conduct: develop/codeOfConduct.md
      - Contributing: develop/contributing.md
      - Releasing: develop/releasing.md
      - Badges: develop/badges.md
  - License: license.md
