<?xml version="1.0" ?>
<SmellBaseline>
  <ManuallySuppressedIssues></ManuallySuppressedIssues>
  <CurrentIssues>
    <ID>ComplexCondition:Dangerfile.df.kts$!isFeatureBranch &amp;&amp; !isReleaseBranch &amp;&amp; !isDependabotBranch &amp;&amp; !isRenovateBranch</ID>
    <ID>LongMethod:PublishingConfigTest.kt$PublishingConfigTest$@Test fun `GIVEN project WHEN configurePublishing() THEN publishing pom configured`()</ID>
    <ID>SwallowedException:TestVersionCatalogAccessor.kt$TestVersionCatalogAccessor$error: Throwable</ID>
    <ID>TooManyFunctions:GradlePluginConventionPlugin.kt$GradlePluginConventionPlugin : PluginPlugin</ID>
  </CurrentIssues>
</SmellBaseline>
