name: CI - Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-release:

    runs-on: ubuntu-latest

    env:
      GITHUB_PACKAGE_DOWNLOAD_USER: ${{ github.actor }}
      GITHUB_PACKAGE_DOWNLOAD_KEY: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PACKAGE_UPLOAD_USER: ${{ github.actor }}
      GITHUB_PACKAGE_UPLOAD_KEY: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Set up Python 3.9
        uses: actions/setup-python@v2          
        with:
          python-version: '3.9'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build project
        run: ./gradlew --no-daemon --stacktrace build

      - name: Publish documentation
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace mkdocsPublish -Prelease

      - name: Publish Release Version
        run: echo "TODO"
