name: CI - Pull Request Validation Test Report

on:
  workflow_run:
    workflows: ['pull-request-validation']
    types:
      - completed

jobs:
  pull-request-validation-test-report:

    runs-on: ubuntu-latest

    concurrency:
      group: validation-report-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: JUnit Tests
          path: '**/build/reports/tests/**/*.xml'
          reporter: java-junit
          artifact: test-results
          fail-on-error: true
