name: CI - Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Set up Python 3.9
        uses: actions/setup-python@v4          
        with:
          python-version: '3.9'

      - name: Setup Android SDK
        uses: bitfunk/setup-android@v1.0.0

      - name: Build project
        run: ./gradlew --no-daemon --stacktrace build

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: junit-test-results
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 1

      - name: Publish documentation
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace mkdocsPublish -Prelease

      - name: Publish Release Version
        run: echo "TODO"

  publish-release-test-report:
    name: "Publish Test Report"
    runs-on: ubuntu-latest
    needs: publish-release
    permissions:
      checks: write
    if: always()

    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v3
        with:
          name: junit-test-results
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/build/test-results/test/TEST-*.xml'
